import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  openFolder: () => ipcRenderer.invoke('dialog:openFolder'),
  scanRepositories: (folderPath: string) => ipcRenderer.invoke('git:scanRepositories', folderPath),
  getRepositoryInfo: (repoPath: string) => ipcRenderer.invoke('git:getRepositoryInfo', repoPath),
  pullRepository: (repoPath: string) => ipcRenderer.invoke('git:pullRepository', repoPath),
  pushRepository: (repoPath: string) => ipcRenderer.invoke('git:pushRepository', repoPath),
  getCommits: (repoPath: string, branch?: string, skip?: number, limit?: number) => ipcRenderer.invoke('git:getCommits', repoPath, branch, skip, limit),
  getFileTree: (repoPath: string, commitHash?: string) => ipcRenderer.invoke('git:getFileTree', repoPath, commitHash),
  getBranches: (repoPath: string) => ipcRenderer.invoke('git:getBranches', repoPath),
  getGitGraph: (repoPath: string, branch?: string) => ipcRenderer.invoke('git:getGitGraph', repoPath, branch),
  getCommitDetails: (repoPath: string, branch?: string, maxCount?: number) => ipcRenderer.invoke('git:getCommitDetails', repoPath, branch, maxCount),
  getCommitFiles: (repoPath: string, commitHash: string) => ipcRenderer.invoke('git:getCommitFiles', repoPath, commitHash),
  getFileDiff: (repoPath: string, commitHash: string, filePath: string) => ipcRenderer.invoke('git:getFileDiff', repoPath, commitHash, filePath),
  getStatus: (repoPath: string) => ipcRenderer.invoke('git:getStatus', repoPath),
  stageFiles: (repoPath: string, filePaths: string[]) => ipcRenderer.invoke('git:stageFiles', repoPath, filePaths),
  unstageFiles: (repoPath: string, filePaths: string[]) => ipcRenderer.invoke('git:unstageFiles', repoPath, filePaths),
  createCommit: (repoPath: string, message: string) => ipcRenderer.invoke('git:createCommit', repoPath, message),
  getWorkingFileDiff: (repoPath: string, filePath: string, staged: boolean) => ipcRenderer.invoke('git:getWorkingFileDiff', repoPath, filePath, staged),
  checkoutBranch: (repoPath: string, branchName: string) => ipcRenderer.invoke('git:checkoutBranch', repoPath, branchName),
  mergeBranch: (repoPath: string, branchName: string, mergeMode?: 'auto' | 'no-ff' | 'ff-only') => ipcRenderer.invoke('git:mergeBranch', repoPath, branchName, mergeMode),
  createBranch: (repoPath: string, branchName: string, startPoint?: string) => ipcRenderer.invoke('git:createBranch', repoPath, branchName, startPoint),
  deleteBranch: (repoPath: string, branchName: string, force: boolean) => ipcRenderer.invoke('git:deleteBranch', repoPath, branchName, force),
  deleteRemoteBranch: (repoPath: string, remoteName: string, branchName: string) => ipcRenderer.invoke('git:deleteRemoteBranch', repoPath, remoteName, branchName),
  renameBranch: (repoPath: string, oldName: string, newName: string, renameRemote: boolean) => ipcRenderer.invoke('git:renameBranch', repoPath, oldName, newName, renameRemote),
  setUpstreamBranch: (repoPath: string, localBranch: string, remoteName: string, remoteBranch: string) => ipcRenderer.invoke('git:setUpstreamBranch', repoPath, localBranch, remoteName, remoteBranch),
  unsetUpstreamBranch: (repoPath: string, branchName: string) => ipcRenderer.invoke('git:unsetUpstreamBranch', repoPath, branchName),
  compareBranches: (repoPath: string, baseBranch: string, compareBranch: string) => ipcRenderer.invoke('git:compareBranches', repoPath, baseBranch, compareBranch),
  getReflog: (repoPath: string, ref?: string, maxCount?: number) => ipcRenderer.invoke('git:getReflog', repoPath, ref, maxCount),
  resetToCommit: (repoPath: string, commitHash: string, mode: 'soft' | 'mixed' | 'hard') => ipcRenderer.invoke('git:resetToCommit', repoPath, commitHash, mode),
  cherryPickCommit: (repoPath: string, commitHash: string) => ipcRenderer.invoke('git:cherryPickCommit', repoPath, commitHash),
  getFileContent: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:getFileContent', repoPath, filePath),
  // Stash operations
  createStash: (repoPath: string, message?: string, includeUntracked?: boolean) => ipcRenderer.invoke('git:createStash', repoPath, message, includeUntracked),
  getStashList: (repoPath: string) => ipcRenderer.invoke('git:getStashList', repoPath),
  applyStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:applyStash', repoPath, index),
  popStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:popStash', repoPath, index),
  dropStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:dropStash', repoPath, index),
  getStashDiff: (repoPath: string, index: number) => ipcRenderer.invoke('git:getStashDiff', repoPath, index),
  getStashFiles: (repoPath: string, index: number) => ipcRenderer.invoke('git:getStashFiles', repoPath, index),
  createBranchFromStash: (repoPath: string, index: number, branchName: string) => ipcRenderer.invoke('git:createBranchFromStash', repoPath, index, branchName),
  clearAllStashes: (repoPath: string) => ipcRenderer.invoke('git:clearAllStashes', repoPath),
  // Conflict resolution
  getConflictedFiles: (repoPath: string) => ipcRenderer.invoke('git:getConflictedFiles', repoPath),
  getFileConflicts: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:getFileConflicts', repoPath, filePath),
  resolveConflict: (repoPath: string, filePath: string, resolution: 'ours' | 'theirs' | 'both', conflictIndex?: number) => ipcRenderer.invoke('git:resolveConflict', repoPath, filePath, resolution, conflictIndex),
  resolveConflictManual: (repoPath: string, filePath: string, content: string) => ipcRenderer.invoke('git:resolveConflictManual', repoPath, filePath, content),
  launchMergeTool: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:launchMergeTool', repoPath, filePath),
  abortMerge: (repoPath: string) => ipcRenderer.invoke('git:abortMerge', repoPath),
  continueMerge: (repoPath: string) => ipcRenderer.invoke('git:continueMerge', repoPath),
  // Search operations
  searchCommits: (repoPath: string, filter: any, limit?: number) => ipcRenderer.invoke('git:searchCommits', repoPath, filter, limit),
  searchCommitsMultiRepo: (repoPaths: string[], filter: any, limit?: number) => ipcRenderer.invoke('git:searchCommitsMultiRepo', repoPaths, filter, limit),
  getAuthors: (repoPath: string) => ipcRenderer.invoke('git:getAuthors', repoPath),
  // Remote management
  getRemotes: (repoPath: string) => ipcRenderer.invoke('git:getRemotes', repoPath),
  addRemote: (repoPath: string, name: string, url: string) => ipcRenderer.invoke('git:addRemote', repoPath, name, url),
  removeRemote: (repoPath: string, name: string) => ipcRenderer.invoke('git:removeRemote', repoPath, name),
  renameRemote: (repoPath: string, oldName: string, newName: string) => ipcRenderer.invoke('git:renameRemote', repoPath, oldName, newName),
  setRemoteUrl: (repoPath: string, name: string, url: string, isPushUrl?: boolean) => ipcRenderer.invoke('git:setRemoteUrl', repoPath, name, url, isPushUrl),
  fetchRemote: (repoPath: string, remoteName: string, prune?: boolean) => ipcRenderer.invoke('git:fetchRemote', repoPath, remoteName, prune),
  pruneRemote: (repoPath: string, remoteName: string) => ipcRenderer.invoke('git:pruneRemote', repoPath, remoteName),
  setUpstream: (repoPath: string, remoteName: string, remoteBranch: string) => ipcRenderer.invoke('git:setUpstream', repoPath, remoteName, remoteBranch),
  getUpstream: (repoPath: string) => ipcRenderer.invoke('git:getUpstream', repoPath),
  // Tag management
  getTags: (repoPath: string) => ipcRenderer.invoke('git:getTags', repoPath),
  createLightweightTag: (repoPath: string, tagName: string, commitHash?: string) => ipcRenderer.invoke('git:createLightweightTag', repoPath, tagName, commitHash),
  createAnnotatedTag: (repoPath: string, tagName: string, message: string, commitHash?: string) => ipcRenderer.invoke('git:createAnnotatedTag', repoPath, tagName, message, commitHash),
  deleteTag: (repoPath: string, tagName: string) => ipcRenderer.invoke('git:deleteTag', repoPath, tagName),
  deleteRemoteTag: (repoPath: string, remoteName: string, tagName: string) => ipcRenderer.invoke('git:deleteRemoteTag', repoPath, remoteName, tagName),
  pushTags: (repoPath: string, remoteName: string, tagName?: string) => ipcRenderer.invoke('git:pushTags', repoPath, remoteName, tagName),
  checkoutTag: (repoPath: string, tagName: string) => ipcRenderer.invoke('git:checkoutTag', repoPath, tagName),
  getTagDetails: (repoPath: string, tagName: string) => ipcRenderer.invoke('git:getTagDetails', repoPath, tagName),
});

