import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  openFolder: () => ipcRenderer.invoke('dialog:openFolder'),
  scanRepositories: (folderPath: string) => ipcRenderer.invoke('git:scanRepositories', folderPath),
  getRepositoryInfo: (repoPath: string) => ipcRenderer.invoke('git:getRepositoryInfo', repoPath),
  pullRepository: (repoPath: string) => ipcRenderer.invoke('git:pullRepository', repoPath),
  pushRepository: (repoPath: string) => ipcRenderer.invoke('git:pushRepository', repoPath),
  getCommits: (repoPath: string, branch?: string, skip?: number, limit?: number) => ipcRenderer.invoke('git:getCommits', repoPath, branch, skip, limit),
  getFileTree: (repoPath: string, commitHash?: string) => ipcRenderer.invoke('git:getFileTree', repoPath, commitHash),
  getBranches: (repoPath: string) => ipcRenderer.invoke('git:getBranches', repoPath),
  getGitGraph: (repoPath: string, branch?: string) => ipcRenderer.invoke('git:getGitGraph', repoPath, branch),
  getCommitDetails: (repoPath: string, branch?: string, maxCount?: number) => ipcRenderer.invoke('git:getCommitDetails', repoPath, branch, maxCount),
  getCommitFiles: (repoPath: string, commitHash: string) => ipcRenderer.invoke('git:getCommitFiles', repoPath, commitHash),
  getFileDiff: (repoPath: string, commitHash: string, filePath: string) => ipcRenderer.invoke('git:getFileDiff', repoPath, commitHash, filePath),
  getStatus: (repoPath: string) => ipcRenderer.invoke('git:getStatus', repoPath),
  stageFiles: (repoPath: string, filePaths: string[]) => ipcRenderer.invoke('git:stageFiles', repoPath, filePaths),
  unstageFiles: (repoPath: string, filePaths: string[]) => ipcRenderer.invoke('git:unstageFiles', repoPath, filePaths),
  createCommit: (repoPath: string, message: string) => ipcRenderer.invoke('git:createCommit', repoPath, message),
  getWorkingFileDiff: (repoPath: string, filePath: string, staged: boolean) => ipcRenderer.invoke('git:getWorkingFileDiff', repoPath, filePath, staged),
  checkoutBranch: (repoPath: string, branchName: string) => ipcRenderer.invoke('git:checkoutBranch', repoPath, branchName),
  mergeBranch: (repoPath: string, branchName: string) => ipcRenderer.invoke('git:mergeBranch', repoPath, branchName),
  getReflog: (repoPath: string, ref?: string, maxCount?: number) => ipcRenderer.invoke('git:getReflog', repoPath, ref, maxCount),
  resetToCommit: (repoPath: string, commitHash: string, mode: 'soft' | 'mixed' | 'hard') => ipcRenderer.invoke('git:resetToCommit', repoPath, commitHash, mode),
  cherryPickCommit: (repoPath: string, commitHash: string) => ipcRenderer.invoke('git:cherryPickCommit', repoPath, commitHash),
  getFileContent: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:getFileContent', repoPath, filePath),
  // Stash operations
  createStash: (repoPath: string, message?: string, includeUntracked?: boolean) => ipcRenderer.invoke('git:createStash', repoPath, message, includeUntracked),
  getStashList: (repoPath: string) => ipcRenderer.invoke('git:getStashList', repoPath),
  applyStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:applyStash', repoPath, index),
  popStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:popStash', repoPath, index),
  dropStash: (repoPath: string, index: number) => ipcRenderer.invoke('git:dropStash', repoPath, index),
  getStashDiff: (repoPath: string, index: number) => ipcRenderer.invoke('git:getStashDiff', repoPath, index),
  getStashFiles: (repoPath: string, index: number) => ipcRenderer.invoke('git:getStashFiles', repoPath, index),
  createBranchFromStash: (repoPath: string, index: number, branchName: string) => ipcRenderer.invoke('git:createBranchFromStash', repoPath, index, branchName),
  clearAllStashes: (repoPath: string) => ipcRenderer.invoke('git:clearAllStashes', repoPath),
  // Conflict resolution
  getConflictedFiles: (repoPath: string) => ipcRenderer.invoke('git:getConflictedFiles', repoPath),
  getFileConflicts: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:getFileConflicts', repoPath, filePath),
  resolveConflict: (repoPath: string, filePath: string, resolution: 'ours' | 'theirs' | 'both', conflictIndex?: number) => ipcRenderer.invoke('git:resolveConflict', repoPath, filePath, resolution, conflictIndex),
  resolveConflictManual: (repoPath: string, filePath: string, content: string) => ipcRenderer.invoke('git:resolveConflictManual', repoPath, filePath, content),
  launchMergeTool: (repoPath: string, filePath: string) => ipcRenderer.invoke('git:launchMergeTool', repoPath, filePath),
  abortMerge: (repoPath: string) => ipcRenderer.invoke('git:abortMerge', repoPath),
  continueMerge: (repoPath: string) => ipcRenderer.invoke('git:continueMerge', repoPath),
});

